version: '3.8'

services:
  ancap-rss:
    build: .
    container_name: ancap-rss-reader
    volumes:
      # Mount data directory for persistent storage
      - ancap-data:/app/data
      - ancap-logs:/app/logs
      # Mount custom feeds configuration (optional override)
      - ./custom_feeds.example.json:/app/custom_feeds.json:ro
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    restart: unless-stopped
    # Network mode host for better terminal integration
    network_mode: host

  # Optional: Development service with live reload
  ancap-rss-dev:
    build: .
    container_name: ancap-rss-dev
    volumes:
      # Mount source code for development
      - ./ANCAP:/app
      - ancap-dev-data:/app/data
      - ancap-dev-logs:/app/logs
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
    profiles:
      - dev
    command: python ancap_rss.py

# Named volumes for data persistence
volumes:
  ancap-data:
    driver: local
  ancap-logs:
    driver: local
  ancap-dev-data:
    driver: local
  ancap-dev-logs:
    driver: local
