name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Lint with flake8
      run: |
        flake8 ancap_rss.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ancap_rss.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test imports
      run: |
        python -c "import feedparser, bs4, requests; print('All modules imported successfully')"
    
    - name: Validate example config
      run: |
        python -c "import json; json.load(open('custom_feeds.example.json')); print('Config is valid JSON')"

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
    
    - name: Run security scan with bandit
      run: |
        bandit -r ancap_rss.py -f json || true
    
    - name: Check dependencies for known vulnerabilities
      run: |
        safety check --json || true

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t ancap-rss:latest .
    
    - name: Test Docker image
      run: |
        docker run --rm ancap-rss:latest python -c "import feedparser, bs4, requests; print('Docker image working')"
